GET http://localhost:3000/api/auth/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoibml0aGlzaCIsImlhdCI6MTcyODI5NjY5MywiZXhwIjoxNzI4MzAwMjkzfQ.fLJTEWo63ISsvLsLm12XhPINPc7pNmCXNFHB0lGzjjo
